version: "3.7"
services:
  web:
    restart: unless-stopped
    build: 
      context: .
    ports:
     - "8000:8000"
    expose:
     - "8000" 
    pull_policy: build
    volumes: 
      - static:/static
  nginx:
   build: ./nginx
   volumes: 
    - static:/static   
    - conf:/etc/nginx/conf.d
   ports:
    - "80:80"
    - "443:443"
   depends_on:
    - web
   labels:
      - "traefik.enable=true"

      - "traefik.http.routers.nginx.rule=Host(`jt.gawa.dtbox.cz`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.middlewares=gawa-jt-redirect-https@docker"

      - "traefik.http.middlewares.nginx.redirectscheme.scheme=https"
      - "traefik.http.middlewares.nginx.redirectscheme.permanent=true"

      - "traefik.http.routers.nginxs.rule=Host(`jt.gawa.dtbox.cz`)"
      - "traefik.http.routers.nginxs.entrypoints=websecure"
      - "traefik.http.routers.nginxs.tls=true"
      - "traefik.http.routers.nginxs.tls.certresolver=letsencrypt"
volumes:
 static:
 conf:
 